  GNU nano 4.8                                                                        dtn7-config.toml                                                                                  
[node]
nodeid = "dtn://node1.dtn"  # Identificador del nodo
host = "127.0.0.1"          # IP en la que escucha el nodo
port = 3000                 # Puerto en el que escucha el nodo

# Nivel de logs para ver los detalles de funcionamiento
log_level = "Debug"

[Store]
path = "/tmp/dtn_store"     # Ruta de almacenamiento para bundles

[Routing]
algorithm = "spray-and-wait"      # Estrategia de enrutamiento (puede ser epidemic, spray-and-wait, etc.)

# Configuraci칩n de REST API (opcional)
#[Agents.REST]
#address = "0.0.0.0:8080"    # Direcci칩n para permitir acceso desde toda la red

[[Listener]]
type = "mtcp"               # Convergence Layer que usar치 `dtn7`
address = ":3000"           # Puerto donde `dtn7` escuchar치 para recibir bundles de `dtn7-rs-lora-ecla`

